config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:passwords], controllers: {
    registrations: 'user/registrations',
    sessions: 'user/sessions'
  }

  devise_for :admin, skip: %i[registrations passwords], controllers: {
    sessions: 'admin/sessions'
  }

  root 'user/homes#top'
  get '/about' => 'user/homes#about', as: 'about'
  patch '/user/edit' => 'user/users#withdrawl', as: 'withdrawl'
  patch '/admin/users/:id/false' => 'admin/users#withdrawl_false', as: 'withdrawl_false'
  patch '/admin/users/:id/true' => 'admin/users#withdrawl_true', as: 'withdrawl_true'
  get 'followings' => 'relationships#followings', as: 'followings'
  get 'followers' => 'relationships#followers', as: 'followers'

  namespace :admin do
    resources :maker_genres
    resources :parts_genres
    resources :users, only: %i[index show edit update destroy withdrawl_false withdrawl_true]
  end

  scope module: :user do
    resources :users, only: %i[index show edit update withdrawl] do
      resources :relationships, only: %i[create destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      collection do
        get 'search'
      end
      member do
        get :goods
      end
    end
    resources :car_posts, only: %i[new create index show edit update destroy] do
      resources :comments, only: %i[create]
      resources :goods, only: %i[create destroy]
    end
    resources :comments, only: %i[destroy edit update]
    resources :maker_genres, only: %i[index show]
    resources :parts_genres, only: %i[index show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/parts_genre.rb
class PartsGenre < ApplicationRecord
  validates :pname, presence: true

  has_many :car_posts
end

app/controllers/admin/parts_genres_controller.rb
class Admin::PartsGenresController < ApplicationController
  def index
    @part = PartsGenre.new
    @parts = PartsGenre.all
    redirect_to root_path unless admin_signed_in?
  end

  def create
    @part = PartsGenre.new(parts_genre_params)
    @part.save
    redirect_to admin_parts_genres_path
  end

  def edit
    @part = PartsGenre.find(params[:id])
    redirect_to root_path unless admin_signed_in?
  end

  def update
    @part = PartsGenre.find(params[:id])
    @part.update(parts_genre_params)
    redirect_to admin_parts_genres_path
  end

  def destroy
    @part = PartsGenre.find(params[:id])
    @part.destroy
    redirect_to admin_parts_genres_path
  end

  private

  def parts_genre_params
    params.require(:parts_genre).permit(:pname)
  end
end

app/controllers/user/parts_genres_controller.rb
class User::PartsGenresController < ApplicationController
  def index
    @pgenres = PartsGenre.all
    redirect_to new_user_session_path unless user_signed_in?
  end

  def show
    @pgenre = PartsGenre.find(params[:id])
    @pgenres = @pgenre.car_posts
    redirect_to new_user_session_path unless user_signed_in?
  end

  private

  def parts_genre_params
    params.permit(:pname, :car_post_id)
  end
end

app/helpers/admin/parts_genres_helper.rb
module Admin::PartsGenresHelper
end

app/helpers/user/parts_genres_helper.rb
module User::PartsGenresHelper
end

app/views/admin/parts_genres/edit.html.erb
<div class="pgenre-edit">

  <h2>PartsGenre Edit</h2>


  <div class="pgenre-form-edit">
    <%= form_with model: @part, url: admin_parts_genre_path(@part.id), method: :patch, local:true do |f| %>
      <%= f.text_field :pname %>
      <%= f.submit "編集" %>
    <% end %>
  </div>

  <div class="pgenre-delete">
    <%= link_to "削除", admin_parts_genre_path(@part.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
  </div>

</div>

app/views/admin/parts_genres/index.html.erb
<div class="admin-pgenre">

  <h2>PartsGenre</h2>

  <div class="genre_form">
    <%= form_with model: @part, url: '/admin/parts_genres', local:true do |f| %>
      <%= f.text_field :pname, placeholder: "パーツジャンル名作成" %>
      <%= f.submit "登録" %>
    <% end %>
  </div>

  <div class="admin-pgenres">

    <% @parts.each do |parts_genre| %>

      <div class="admin-pgenre-box">

        <div class="admin-pgenre-name">
          <%= parts_genre.pname %>
        </div>

        <div class="admin-pgenre-edit">
          <%= link_to "編集", edit_admin_parts_genre_path(parts_genre.id) %>
        </div>

      </div>

    <% end %>

  </div>

</div>