config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:passwords], controllers: {
    registrations: 'user/registrations',
    sessions: 'user/sessions'
  }

  devise_for :admin, skip: %i[registrations passwords], controllers: {
    sessions: 'admin/sessions'
  }

  root 'user/homes#top'
  get '/about' => 'user/homes#about', as: 'about'
  patch '/user/edit' => 'user/users#withdrawl', as: 'withdrawl'
  patch '/admin/users/:id/false' => 'admin/users#withdrawl_false', as: 'withdrawl_false'
  patch '/admin/users/:id/true' => 'admin/users#withdrawl_true', as: 'withdrawl_true'
  get 'followings' => 'relationships#followings', as: 'followings'
  get 'followers' => 'relationships#followers', as: 'followers'

  namespace :admin do
    resources :maker_genres
    resources :parts_genres
    resources :users, only: %i[index show edit update destroy withdrawl_false withdrawl_true]
  end

  scope module: :user do
    resources :users, only: %i[index show edit update withdrawl] do
      resources :relationships, only: %i[create destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      collection do
        get 'search'
      end
      member do
        get :goods
      end
    end
    resources :car_posts, only: %i[new create index show edit update destroy] do
      resources :comments, only: %i[create]
      resources :goods, only: %i[create destroy]
    end
    resources :comments, only: %i[destroy edit update]
    resources :maker_genres, only: %i[index show]
    resources :parts_genres, only: %i[index show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 20 }
  validates :car_name, presence: true, length: { maximum: 20 }
  validates :maker_genre_id, presence: true

  has_one_attached :plofile_image

  belongs_to :maker_genre
  has_many :car_posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :goods, dependent: :destroy
  has_many :good_car_posts, through: :goods, source: :car_post

  has_many :relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy

  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def gooded_by?(car_post_id)
    goods.where(car_post_id: car_post_id).exists?
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all.page(params[:page]).per(20)
    redirect_to root_path unless admin_signed_in?
  end

  def show
    @user = User.find(params[:id])
    @carposts = @user.car_posts.order(created_at: :desc).page(params[:page]).per(10)
    redirect_to new_user_session_path unless admin_signed_in?
  end

  def edit
    @user = User.find(params[:id])
    redirect_to root_path unless admin_signed_in?
  end

  def update
    @user = User.find(params[:id])
    if  @user.update(user_params)
      redirect_to admin_user_path(@user.id)
    else
      render "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end

  def withdrawl_false
    redirect_to root_path unless admin_signed_in?
    @user = User.find(params[:id])
    @user.update(is_deleted: false)
    redirect_to admin_user_path(@user.id)
  end

  def withdrawl_true
    redirect_to root_path unless admin_signed_in?
    @user = User.find(params[:id])
    @user.update(is_deleted: true)
    redirect_to admin_user_path(@user.id)
  end

  private

  def user_params
    params.require(:user).permit(:name, :car_name, :email, :is_deleted, :maker_genre_id, :plofile_image)
  end
end

app/controllers/user/car_posts_controller.rb
class User::CarPostsController < ApplicationController
  def new
    @carpost = CarPost.new
    　redirect_to new_user_session_path unless user_signed_in?
  end

  def create
    @carpost = CarPost.new(car_post_params)
    @carpost.user_id = current_user.id
    if @carpost.save
      redirect_to car_post_path(@carpost.id)
    else
      render 'new'
    end
  end

  def index
    @carposts = CarPost.all.page(params[:page]).per(5).order(created_at: :desc)
    redirect_to new_user_session_path unless user_signed_in? or admin_signed_in?
  end

  def show
    @carpost = CarPost.find(params[:id])
    @comments = @carpost.comments
    @comment = Comment.new
    redirect_to new_user_session_path unless user_signed_in? or admin_signed_in?
  end

  def edit
    @carpost = CarPost.find(params[:id])
    redirect_to root_path unless current_user.id == @carpost.user.id
  end

  def update
    @carpost = CarPost.find(params[:id])
    if @carpost.update(car_post_params)
      redirect_to car_post_path(@carpost.id)
    else
      render "edit"
    end
  end

  def destroy
    @carpost = CarPost.find(params[:id])
    @carpost.destroy
    redirect_to car_posts_path
  end

  private

  def car_post_params
    params.require(:car_post).permit(:title, :message, :user_id, :parts_genre_id, :comment_id, car_images: [])
  end
end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController
  def create
    @carpost = CarPost.find(params[:car_post_id])
    @comment = @carpost.comments.build(comment_params)
    @comment.user_id = current_user.id
    if  @comment.save
      render :index
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to car_post_path(@comment.car_post.id)
    else
      render 'edit'
    end
  end

  def destroy
    Comment.find(params[:id]).destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def comment_params
    params.require(:comment).permit(:post_comment, :car_post_id, :user_id)
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/goods_controller.rb
class User::GoodsController < ApplicationController
  before_action :set_car_post

  def create
    @good = Good.create(user_id: current_user.id, car_post_id: @carpost.id)
  end

  def destroy
    good = Good.find_by(user_id: current_user.id, car_post_id: @carpost.id)
    good.destroy
  end

  private

  def set_car_post
    @carpost = CarPost.find(params[:car_post_id])
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
    @carposts = CarPost.all.limit(5).order(created_at: :desc)
  end

  def about
  end
end

app/controllers/user/maker_genres_controller.rb
class User::MakerGenresController < ApplicationController
  def index
    @mgenres = MakerGenre.all
    redirect_to new_user_session_path unless user_signed_in?
  end

  def show
    @mgenre = MakerGenre.find(params[:id])
    @mgenres = @mgenre.users
    redirect_to new_user_session_path unless user_signed_in?
  end

  private

  def maker_genre_params
    params.permit(:mname, :user_id)
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/parts_genres_controller.rb
class User::PartsGenresController < ApplicationController
  def index
    @pgenres = PartsGenre.all
    redirect_to new_user_session_path unless user_signed_in?
  end

  def show
    @pgenre = PartsGenre.find(params[:id])
    @pgenres = @pgenre.car_posts
    redirect_to new_user_session_path unless user_signed_in?
  end

  private

  def parts_genre_params
    params.permit(:pname, :car_post_id)
  end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/relationships_controller.rb
class User::RelationshipsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    current_user.follow(params[:user_id])
  end

  def destroy
    @user = User.find(params[:user_id])
    current_user.unfollow(params[:user_id])
  end

  def followings
    @user = User.find(params[:user_id])
    @users = @user.followings.page(params[:page]).per(10)
    redirect_to new_user_session_path unless user_signed_in?
  end

  def followers
    @user = User.find(params[:user_id])
    @users = @user.followers.page(params[:page]).per(10)
    redirect_to new_user_session_path unless user_signed_in?
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  before_action :user_state, only: [:create]
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def user_state
    @user = User.find_by(email: params[:user][:email])
    if @user && (@user.valid_password?(params[:user][:password]) && (@user.is_deleted == true))
      redirect_to new_user_session_path
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  def index
    @users = User.all.page(params[:page]).per(20)
    redirect_to new_user_session_path unless user_signed_in?
  end

  def show
    @user = User.find(params[:id])
    @carposts = @user.car_posts.order(created_at: :desc).page(params[:page]).per(5)
    if admin_signed_in?
      redirect_to admin_user_path(@user.id)
    else
      redirect_to new_user_session_path unless user_signed_in?
    end
  end

  def edit
    @user = User.find(params[:id])
    redirect_to root_path unless current_user.id == @user.id
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render "edit"
    end
  end

  def goods
    @user = User.find(params[:id])
    goods = Good.where(user_id: @user.id).pluck(:car_post_id)
    @good_car_posts = CarPost.find(goods)
    @good_car_posts = Kaminari.paginate_array(@good_car_posts).page(params[:page]).per(5)
  end

  def withdrawl
    @user = current_user
    redirect_to root_path unless current_user.id == @user.id
    @user.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :car_name, :email, :is_deleted, :maker_genre_id, :plofile_image)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/car_posts_helper.rb
module User::CarPostsHelper
end

app/helpers/user/comments_helper.rb
module User::CommentsHelper
end

app/helpers/user/goods_helper.rb
module User::GoodsHelper
end

app/views/admin/users/edit.html.erb
<div class="admin-user-edit-form">
　　<%= form_with model: @user, url: admin_user_path(@user.id), method: :patch, local:true do |f| %>
　　<%= render 'layouts/error_messages', model: f.object %>

      <h2>管理者ユーザー編集</h2>
      <div class="admin-user-edit-item">
        <div class="admin-user-edit-item-label">
          <%= f.label :name, "ユーザーネーム" %>
        </div>
        <div class="admin-user-edit-item-content">
          <%= f.text_field :name, placeholder: "※20文字まで入力できます" %>
        </div>
      </div>

      <div class="admin-user-edit-item">
        <div class="admin-user-edit-item-label">
          <%= f.label :maker_genre_id, "メーカー" %>
        </div>
        <div class="admin-user-edit-item-content">
          <%= f.collection_select :maker_genre_id, MakerGenre.all, :id, :mname, { include_blank: "選択して下さい" }, class: "select" %>
        </div>
      </div>

      <div class="admin-user-edit-item">
        <div class="admin-user-edit-item-label">
          <%= f.label :car_name, "車名" %>
        </div>
        <div class="admin-user-edit-item-content">
          <%= f.text_field :car_name, placeholder: "※20文字まで入力できます" %>
        </div>
      </div>

      <div class="admin-user-edit-item">
        <div class="admin-user-edit-item-label">
          <%= f.label :email, "Eメール" %>
        </div>
        <div class="admin-user-edit-item-content">
          <%= f.text_field :email %>
        </div>
      </div>

      <div class="admin-user-edit-item">
        <div class="admin-user-edit-image">
          <%= f.label :plofile_image, "ユーザーアイコンを選択" %>
          <%= f.file_field :plofile_image %>
        </div>
        <div class="admin-user-edit-plofile-image">
          <img id="preview" class="edit-plofile-image">
        </div>
      </div>

      <div class="admin-user-edit-item">
        <div class="admin-user-edit-submit">
          <%= f.submit "編集" %>
        </div>
      </div>

  <% end %>
</div>

<script>
$('#user_plofile_image').on('change', function (e) {
    var reader = new FileReader();
    reader.onload = function (e) {
        $("#preview").attr('src', e.target.result);
    };
    reader.readAsDataURL(e.target.files[0]);
  });
</script>

app/views/admin/users/index.html.erb
<div class="admin-index-users">

  <h2>Users!</h2>

  <% unless @search_users.present? %>
    <p>該当するユーザーがいません</p>
  <% else %>

    <% @search_users.each do |user| %>

      <div class="admin-index-user">
        <div class="admin-index-user-content">
          <% if user.plofile_image.attached? %>

            <%= link_to admin_user_path(user.id) do %>
              <%= image_tag user.plofile_image, class: "plofile-image" %>
            <% end %>

          <% else %>

            <%= link_to admin_user_path(user.id) do %>
              <%= image_tag asset_path("no_image.jpg"), class: "plofile-image" %>
            <% end %>

          <% end %>


            <div class="admin-index-user-right">
              <div class="admin-index-user-name"><%= link_to user.name, admin_user_path(user.id) %></div>
              <div class="admin-index-user-car"><%= link_to user.maker_genre.mname, admin_user_path(user.id) %>. <%= link_to user.car_name, admin_user_path(user.id) %></div>
            </div>

            <% if user.is_deleted == false %>
              <div class="is_deleted-false"><i class="fa-solid fa-face-grin-beam"></i></div>
            <% else %>
              <div class="is_deleted-true"><i class="fa-solid fa-face-dizzy"></i></div>
            <% end %>

        </div>


      </div>
    <% end %>

  <% end %>

  <div class="page">
    <%= paginate @search_users %>
  </div>

</div>

app/views/admin/users/show.html.erb
<div class="admin-show-user">

  <div class="admin-show-user-content">

    <div class="admin-show-user-box">

      <div class="admin-show-user-status">

        <table>
          <tr>
            <th>ユーザー名</td>
            <td><%= @user.name %></td>
          </tr>
          <tr>
            <th>メーカー</td>
            <td><%= @user.maker_genre.mname %></td>
          </tr>
          <tr>
            <th>車名</td>
            <td><%= @user.car_name %></td>
          </tr>
          <tr>
            <th>Eメール</td>
            <td><%= @user.email %></td>
          </tr>
          <tr>
            <th>ステータス</th>
            <td>
              <% if @user.is_deleted == false %>
                <%= link_to withdrawl_true_path, method: :patch, "data-confirm" => "アカウントを停止しますか？" do %>
                  <div class="is_deleted-false">起動中</div>
                <% end %>
              <% else %>
                <%= link_to withdrawl_false_path, method: :patch, "data-confirm" => "アカウントを再開しますか？" do %>
                    <div class="is_deleted-true">停止中</div>
                <% end %>
              <% end %>

            </td>
          </tr>
        </table>

        <div class="admin-show-user-edit">
          <div class="admin-show-user-edit-btn"><%= link_to "ユーザー編集", edit_admin_user_path(@user.id) %></div>
          <div class="admin-show-user-delete-btn"><%= link_to "ユーザー削除", admin_user_path(@user.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></div>
        </div>

      </div>

      <div class="admin-show-user-image">
        <% if @user.plofile_image.attached? %>
          <%= link_to @user.plofile_image do %>
            <%= image_tag @user.plofile_image, class: "admin-plofile-image" %>
          <% end %>
        <% else %>
            <%= image_tag asset_path("no_image.jpg"), class: "admin-plofile-image" %>
        <% end %>
      </div>

    </div>

    <div class="admin-show-user-count">
      <div class="admin-show-user-count-area">フォロー. <%= @user.followings.count %></div>
      <div class="admin-show-user-count-area">フォロワー. <%= @user.followers.count %></div>
      <div class="admin-show-user-count-area">CarPosts. <%= @user.car_posts.count %></div>
    </div>

  </div>

  <div class="admin-show-user-carposts">
    <h2>投稿一覧</h2>
  </div>

  <%  unless @carposts.present? %>
    <p>投稿がありません</p>
  <% else %>

  <% @carposts.each do |carpost| %>
    <div class="admin-show-user-carpost">

      <div class="admin-show-user-carpost-time">
        <%= carpost.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
      </div>

      <div class="slider">
        <% carpost.car_images.each do |carimages| %>
          <%= link_to car_post_path(carpost.id) do %>
             <%= image_tag carimages, class: "car-image" %>
          <% end %>
        <% end %>
      </div>

      <div class="admin-show-user-carpost-text">

        <div class="admin-show-user-genre">
          ジャンル:<%= carpost.parts_genre.pname %>
        </div>

        <div class="admin-show-user-btn">
          <div class="admin-show-user-good">
            <i class="fa-solid fa-heart"></i>いいね！<%= Good.where(car_post_id: carpost.id).count %>
          </div>
          <div class="admin-show-user-comment-count">
            <i class="fa-regular fa-comment-dots"></i>コメント<%= Comment.where(car_post_id: carpost.id).count %>
          </div>
        </div>

        <div class="admin-show-user-title">
          <%= carpost.title %>
        </div>

      </div>

    </div>
  <% end %>
  <% end %>

  <div class="page">
    <%= paginate @carposts %>
  </div>

</div>

<script>
window.onload = function () {
  $(function() {
    $('.slider').slick({
      speed: 1000,

      prevArrow: '<button class="slide-arrow prev-arrow"></button>',
      nextArrow: '<button class="slide-arrow next-arrow"></button>'
    });
  });

  $('input').on('change', function () {
      var file = $(this).prop('files')[0];
      $('p').text(file.name);
  });
};

</script>